src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'Cette adresse email est déjà utilisée.')]
#[HasLifecycleCallbacks]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\NotBlank(message: 'Veuillez saisir une adresse email.')]
    #[Assert\Email(message: 'Veuillez saisir une adresse email valide.')]
    #[Assert\Length(max: 180, maxMessage: 'L\'adresse email ne peut pas dépasser {{ limit }} caractères.')]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Assert\NotBlank(message: 'Veuillez saisir un mot de passe.')]
    #[Assert\Length(min: 8, minMessage: 'Le mot de passe doit contenir au moins {{ limit }} caractères.')]
    private ?string $password = null;


    #[Assert\Length(min: 8, minMessage: 'Le mot de passe doit contenir au moins {{ limit }} caractères.')]
    private ?string $newPassword=null;


    #[ORM\Column(length: 10)]
    #[Assert\NotBlank(message: 'Veuillez sélectionner une civilité.')]
    private ?string $gender = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Veuillez saisir un prénom.')]
    #[Assert\Length(min: 2, max: 255, minMessage: 'Le prénom doit contenir au moins {{ limit }} caractères.', maxMessage: 'Le prénom ne peut pas dépasser {{ limit }} caractères.')]
    private ?string $firstName = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Veuillez saisir un nom.')]
    #[Assert\Length(min: 2, max: 255, minMessage: 'Le nom doit contenir au moins {{ limit }} caractères.', maxMessage: 'Le nom ne peut pas dépasser {{ limit }} caractères.')]
    private ?string $lastName = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Question::class, orphanRemoval: true)]
    private Collection $questions;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(length: 255)]
    private ?string $picture = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Vote::class, orphanRemoval: true)]
    private Collection $votes;

    public function __construct()
    {
        $this->questions = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->votes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): static
    {
        $this->gender = $gender;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): static
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * @return Collection<int, Question>
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): static
    {
        if (!$this->questions->contains($question)) {
            $this->questions->add($question);
            $question->setAuthor($this);
        }

        return $this;
    }

    public function removeQuestion(Question $question): static
    {
        if ($this->questions->removeElement($question)) {
            // set the owning side to null (unless already changed)
            if ($question->getAuthor() === $this) {
                $question->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }


    public function getFullName(): string
    {
        return $this->firstName . ' ' . $this->lastName;
    }

    /**
     * Get the value of newPassword
     */ 
    public function getNewPassword(): ?string
    {
        return $this->newPassword;
    }


    public function setNewPassword($newPassword):self
    {
        $this->newPassword = $newPassword;

        return $this;
    }

    /**
     * @return Collection<int, Vote>
     */
    public function getVotes(): Collection
    {
        return $this->votes;
    }

    public function addVote(Vote $vote): static
    {
        if (!$this->votes->contains($vote)) {
            $this->votes->add($vote);
            $vote->setAuthor($this);
        }

        return $this;
    }

    public function removeVote(Vote $vote): static
    {
        if ($this->votes->removeElement($vote)) {
            // set the owning side to null (unless already changed)
            if ($vote->getAuthor() === $this) {
                $vote->setAuthor(null);
            }
        }

        return $this;
    }

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function setCreatedAtValue(): void
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    #[ORM\PrePersist]
    public function generateHash(): void
    {
        $this->password = password_hash($this->password, PASSWORD_DEFAULT);
    }

    /* #[ORM\PreUpdate]
    public function generateHashOnUpdate(): void
    {
       $this->newPassword && $this->password = password_hash($this->newPassword, PASSWORD_DEFAULT);
    } */

}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Service\Uploader;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;


class UserController extends AbstractController
{


    #[Route('/user', name: 'app_current_user_profile')]
    #[IsGranted('IS_AUTHENTICATED_FULLY')]
    public function currentUserProfile(Uploader $uploader, Request $request, EntityManagerInterface $em, UserPasswordHasherInterface $userPassword): Response
    {
        $user = $this->getUser();

        $userForm = $this->createForm(UserType::class, $user);


        $userForm->remove('password'); // Suppression du champ password du formulaire

        // Ajout du champ newPassword au formulaire pour permettre la modification du mot de passe
        $userForm->add('newPassword', RepeatedType::class, [
            'type' => PasswordType::class,
            'invalid_message' => 'Les mots de passe doivent correspondre.',
            'required' => false,
            'first_options' => ['label' => 'Nouveau mot de passe', 'required' => false],
            'second_options' => ['label' => 'Confirmer le nouveau mot de passe', 'required' => false],
        ]);

        $userForm->handleRequest($request);

        if ($userForm->isSubmitted() && $userForm->isValid()) {

            $newPassword = $user->getNewPassword();

            if ($newPassword) {
                $hash = $userPassword->hashPassword($user, $newPassword);
                $user->setPassword($hash);
            }

            $picture = $userForm->get('pictureFile')->getData();
            if ($picture) {
                $user->setPicture($uploader->uploadProfilImage($picture, $user->getPicture()));
            }

            $em->flush();

            notyf()
                ->position('x', 'center')
                ->position('y', 'top')
                ->duration(5000)
                ->dismissible(true)
                ->addSuccess('Votre profil a bien été mis à jour.');


            /* $this->addFlash('info', 'Votre profil a bien été mis à jour.'); */
        }

        return $this->render('user/index.html.twig', [
            'form' => $userForm->createView(),
        ]);
    }

    #[Route('/user/{id}/edit', name: 'app_user_edit')]
    #[IsGranted('IS_AUTHENTICATED_FULLY')]
    public function editCurrentUserProfile(User $user, $id, Uploader $uploader, Request $request, EntityManagerInterface $em, UserPasswordHasherInterface $userPassword): Response
    {

        $user = $this->getUser();

        $userForm = $this->createForm(UserType::class, $user);


        $userForm->remove('password'); // Suppression du champ password du formulaire

        // Ajout du champ newPassword au formulaire pour permettre la modification du mot de passe
        /*  $userForm->add('newPassword', RepeatedType::class, [
            'type' => PasswordType::class,
            'invalid_message' => 'Les mots de passe doivent correspondre.',
            'required' => false,
            'first_options' => ['label' => 'Nouveau mot de passe', 'required' => false],
            'second_options' => ['label' => 'Confirmer le nouveau mot de passe', 'required' => false],
        ]);
 */
        $userForm->handleRequest($request);

        if ($userForm->isSubmitted() && $userForm->isValid()) {

            /*  $newPassword = $user->getNewPassword();

            if ($newPassword) {
                $hash = $userPassword->hashPassword($user, $newPassword);
                $user->setPassword($hash);
            } */

            $picture = $userForm->get('pictureFile')->getData();
            if ($picture) {
                $user->setPicture($uploader->uploadProfilImage($picture, $user->getPicture()));
            }

            $em->flush();
            /*  $this->addFlash('info', 'Votre profil a bien été mis à jour.'); */
            notyf()
                ->position('x', 'center')
                ->position('y', 'top')
                ->duration(5000)
                ->dismissible(true)
                ->addSuccess('Votre profil a bien été mis à jour.');
        }

        return $this->render('user/edit.html.twig', [
            'form' => $userForm->createView(),
        ]);
    }


    #[Route('/user/{id}/change-password', name: 'app_user_change_password')]
    #[IsGranted('IS_AUTHENTICATED_FULLY')]
    public function changeCurrentUserProfile(User $user, $id, Uploader $uploader, Request $request, EntityManagerInterface $em, UserPasswordHasherInterface $userPassword): Response
    {

        $user = $this->getUser();

        $userForm = $this->createForm(UserType::class, $user);


        $userForm->remove('gender');
        $userForm->remove('email');
        $userForm->remove('firstName');
        $userForm->remove('lastName');
        $userForm->remove('pictureFile');
        $userForm->remove('password');


        // Ajout du champ newPassword au formulaire pour permettre la modification du mot de passe
        $userForm->add('newPassword', RepeatedType::class, [
            'type' => PasswordType::class,
            'invalid_message' => 'Les mots de passe doivent correspondre.',
            'required' => false,
            'first_options' => ['label' => 'Nouveau mot de passe', 'required' => false],
            'second_options' => ['label' => 'Confirmer le nouveau mot de passe', 'required' => false],
        ]);

        $userForm->handleRequest($request);

        if ($userForm->isSubmitted() && $userForm->isValid()) {

            $newPassword = $user->getNewPassword();

            if ($newPassword) {
                $hash = $userPassword->hashPassword($user, $newPassword);
                $user->setPassword($hash);
            }


            $em->flush();
            /* $this->addFlash('info', 'Votre mot de passe a bien été mis à jour.'); */


            notyf()
                ->position('x', 'center')
                ->position('y', 'top')
                ->duration(5000)
                ->dismissible(true)
                ->addSuccess('Votre mot de passe a bien été mis à jour.');

            return $this->redirectToRoute('app_current_user_profile');
        }

        return $this->render('user/reset_password.html.twig', [
            'form' => $userForm->createView(),
        ]);
    }





    #[Route('/user/{id}', name: 'app_user_profile')]
    #[IsGranted('IS_AUTHENTICATED_REMEMBERED')]
    public function userProfile(User $user): Response
    {
        $currentUser = $this->getUser();

        if ($currentUser === $user) {
            return $this->redirectToRoute('app_current_user_profile');
        }

        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }
}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ parent() }}
	- Mon Profile
{% endblock %}

{% block body %}
	<div class="block mb-20">
		<h1 class="pb-30 text-center">Modifier mon Profile</h1>
		{{ form_start(form) }}
		{{ form_row(form.gender, {'label': false})}}
		{{ form_row(form.firstName) }}
		{{ form_row(form.lastName) }}
		{{ form_row(form.email) }}
		{{ form_rest(form) }}
		<div style="width: 200px; margin: 0 auto; display: block;text-align: center; margin-top: 20px;">
			<button class="btn btn-warning">Mettre à jour</button>
		</div>
		{{ form_end(form) }}

	</div>

	{# 	<div class="block mb-20">
			<h3 class="pb-30">Mes questions</h3>
			<ul>
				{% for question in app.user.questions %}
					<li>
						<a href="{{ path('app_question_show', {'id': question.id}) }}">{{ question.title }}</a>
					</li>
				{% endfor %}
			</ul>
		</div>
	
		<div class="block mb-20">
			<h3 class="pb-30">Mes réponses</h3>
	
			<ul>
				{% for comment in app.user.comments %}
					<li>
						-
						<a href="{{ path('app_question_show', {'id': comment.question.id}) }}">{{ comment.content|slice(0, 150) }}...</a>
					</li>
				{% endfor %}
			</ul>
		</div> #}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ parent() }}
	- Mon Profile
{% endblock %}


{% block body %}
	<div class="block mb-20">
		{# {{ form_start(form) }}
						{{ form_row(form.gender, {'label': false})}}
						{{ form_row(form.firstName) }}
						{{ form_row(form.lastName) }}
						{{ form_row(form.email) }}
						{{ form_rest(form) }}
						<div style="width: 200px; margin: 0 auto; display: block;text-align: center; margin-top: 20px;">
							<button class="btn btn-warning">Mettre à jour</button>
						</div>
						{{ form_end(form) }} #}

		<div class="profile-container">
			<div class="profile-header">
				<img src="{{app.user.picture}}" alt="Profile Picture">

				<h2>
					{{app.user.firstName|capitalize}}
					{{app.user.lastName|upper}}
				</h2>
				<p>
					<b>Email</b>:
					{{app.user.email}}
				</p>

			</div>
			<div class="profile-body">
				<h2>Mes participations</h2>
				<ul>
					<li>
						<b>Questions</b>:
						{{app.user.questions|length}}
					</li>
					<li>
						<b>Réponses</b>:
						{{app.user.comments|length}}
					</li>
			</div>
			<p class="profile-footer mt-30">
				Membre depuis le {{app.user.createdAt|date('d/m/Y')}}
			</p>
		</div>


	</div>

	{# 	<div class="block mb-20">
				<h3 class="pb-30">Mes questions</h3>
				<ul>
					{% for question in app.user.questions %}
						<li>
							<a href="{{ path('app_question_show', {'id': question.id}) }}">{{ question.title }}</a>
						</li>
					{% endfor %}
				</ul>
			</div>
		
			<div class="block mb-20">
				<h3 class="pb-30">Mes réponses</h3>
		
				<ul>
					{% for comment in app.user.comments %}
						<li>
							-
							<a href="{{ path('app_question_show', {'id': comment.question.id}) }}">{{ comment.content|slice(0, 150) }}...</a>
						</li>
					{% endfor %}
				</ul>
			</div> #}
{% endblock %}

templates/user/reset_password.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ parent() }}
	- Mon Profile
{% endblock %}

{% block body %}
	<div class="block mb-20">
		<h1 class="pb-30 text-center">Modifier mon mot de passe</h1>
		{{ form_start(form) }}
		{{ form_rest(form) }}
		<div style="width: 200px; margin: 0 auto; display: block;text-align: center; margin-top: 20px;">
			<button class="btn btn-warning">Mettre à jour</button>
		</div>
		{{ form_end(form) }}

	</div>

{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ parent() }}
	- Profile
	{{user.fullName}}
{% endblock %}


{% block body %}

	<div class="block">
		<h2 class="pb-20 text-center">
			Profile de
			{{user.fullName}}

		</h2>

		<div class="d-flex flex-row-nowrap">
			<img src="{{user.picture}}" alt="profil_de_{{user.fullName}}" class="mr-10 profile-picture">
			<ul>
				<li class="mb-10">
					<strong class=="mr-10">Prénom :</strong>
					{{user.firstName}}
				</li>
				<li class="mb-10">
					<strong class=="mr-10">Nom :</strong>
					{{user.lastName}}
				</li>
				<li class="mb-10">
					<strong class=="mr-10">Email :</strong>
					{{user.email}}
				</li>
				<li class="mb-10">
					<strong class=="mr-10">Membre depuis le :</strong>
					{{user.createdAt|date('d/m/Y')}}
				</li>
			</ul>
			<div class="ml-auto">
				{% if user.comments is not null and user.comments|length > 0  %}

					<p class="mb-10">
						<strong>Nb Commentaires :</strong>
						{{user.comments|length}}
					</p>
				{% else %}
					<p class="text-center">Aucun commentaire</p>
				{% endif %}

				{% if user.questions is not null and user.questions|length > 0 %}
					<p class="mb-10">
						<strong>Nb Articles :</strong>
						{{user.questions|length}}
					</p>
				{% else %}
					<p class="text-center">Aucune question</p>
				{% endif %}
			</div>
		</div>

	</div>

	{% if user.questions|length > 0 %}
		<div class="block mb-20 mt-20">
			<h3 class="pb-30 text-center">Question</h3>
			<ul class="list-unstyled d-flex flex-column">
				{% for question in user.questions %}
					<li class="mb-20 d-flex justify-content-between">
						<a href="{{ path('app_question_show', {'id': question.id}) }}">
							{{ question.title }}
							{% if question.rating > 2 %}
								<i class="fas fa-thumbs-up"></i>
							{% else %}
								<i class="fas fa-thumbs-down"></i>
							{% endif %}
						</a>

						<span>{{ question.createdAt|ago(locale='fr')}}</span>
					</li>


				{% endfor %}
			</ul>
		</div>
	{% endif %}


	{% if user.comments|length > 0 %}
		<div class="block mb-20 mt-20">
			<h3 class="pb-30 text-center">Réponses</h3>
			<ul class="list-unstyled">
				{% for comment in user.comments %}
					<li class="mb-20 justify-content-between">
						<a href="{{ path('app_question_show', {'id': comment.question.id}) }}">
							<i class="fa-solid fa-question"></i>
							{{ comment.content|slice(0, 150) }}...</a>
						{% if comment.rating > 2 %}
							<i class="fas fa-thumbs-up"></i>
							{% if comment.rating != 0 %}
								{{comment.rating|abs}}
							{% endif %}
						{% else %}
							<i class="fas fa-thumbs-down"></i>
							{% if comment.rating != 0 %}
								{{comment.rating|abs}}
							{% endif %}

						{% endif %}

						<p>{{ comment.createdAt|ago(locale='fr')}}</p>
					</li>

				{% endfor %}
			</ul>
		</div>
	{% endif %}
{% endblock %}